export const stateTaxRates: Record<string, number> = {
  Alabama: 5,
  Alaska: 0,
  Arizona: 4,
  Arkansas: 5,
  California: 9,
  Colorado: 4.5,
  Connecticut: 6,
  Delaware: 6,
  "District of Columbia": 8,
  Florida: 0,
  Georgia: 5,
  Hawaii: 8,
  Idaho: 5,
  Illinois: 5,
  Indiana: 3,
  Iowa: 6,
  Kansas: 5,
  Kentucky: 5,
  Louisiana: 4,
  Maine: 7,
  Maryland: 5,
  Massachusetts: 5,
  Michigan: 4,
  Minnesota: 7,
  Mississippi: 5,
  Missouri: 5,
  Montana: 6,
  Nebraska: 5,
  Nevada: 0,
  "New Hampshire": 0,
  "New Jersey": 6,
  "New Mexico": 5,
  "New York": 8,
  "North Carolina": 5,
  "North Dakota": 2,
  Ohio: 4,
  Oklahoma: 5,
  Oregon: 8,
  Pennsylvania: 3,
  "Rhode Island": 6,
  "South Carolina": 5,
  "South Dakota": 0,
  Tennessee: 0,
  Texas: 0,
  Utah: 5,
  Vermont: 6,
  Virginia: 5,
  Washington: 0,
  "West Virginia": 5,
  Wisconsin: 6,
  Wyoming: 0,
};

export function getStateTaxRate(state: string): string {
  const rate = stateTaxRates[state];
  return rate !== undefined ? String(rate) : "5";
}
